var annotated_dup =
[
    [ "_function_list", "struct__function__list.html", "struct__function__list" ],
    [ "attribute_value", "structattribute__value.html", "structattribute__value" ],
    [ "auth_ctx_t", "structauth__ctx__t.html", "structauth__ctx__t" ],
    [ "auth_struct", "structauth__struct.html", "structauth__struct" ],
    [ "jsmn_parser", "structjsmn__parser.html", "structjsmn__parser" ],
    [ "jsmntok", "structjsmntok.html", "structjsmntok" ],
    [ "optimizer_complex_var_t", "structoptimizer__complex__var__t.html", "structoptimizer__complex__var__t" ],
    [ "optimizer_function_element_t", "unionoptimizer__function__element__t.html", "unionoptimizer__function__element__t" ],
    [ "optimizer_log_var_t", "structoptimizer__log__var__t.html", "structoptimizer__log__var__t" ],
    [ "optimizer_operator_t", "structoptimizer__operator__t.html", "structoptimizer__operator__t" ],
    [ "pap_action_list_", "structpap__action__list__.html", "structpap__action__list__" ],
    [ "pap_plugin_get_args_t", "structpap__plugin__get__args__t.html", "structpap__plugin__get__args__t" ],
    [ "pap_plugin_has_args_t", "structpap__plugin__has__args__t.html", "structpap__plugin__has__args__t" ],
    [ "pap_plugin_len_args_t", "structpap__plugin__len__args__t.html", "structpap__plugin__len__args__t" ],
    [ "pap_policy_id_signature_t", "structpap__policy__id__signature__t.html", "structpap__policy__id__signature__t" ],
    [ "pap_policy_object_t", "structpap__policy__object__t.html", "structpap__policy__object__t" ],
    [ "pap_policy_t", "structpap__policy__t.html", "structpap__policy__t" ],
    [ "pap_policy_value_t", "structpap__policy__value__t.html", "structpap__policy__value__t" ],
    [ "pdp_action_t", "structpdp__action__t.html", "structpdp__action__t" ],
    [ "pep_plugin_args_t", "structpep__plugin__args__t.html", "structpep__plugin__args__t" ],
    [ "pip_attribute_object_t", "structpip__attribute__object__t.html", "structpip__attribute__object__t" ],
    [ "pip_plugin_args_t", "structpip__plugin__args__t.html", "structpip__plugin__args__t" ],
    [ "pip_plugin_string_arg_t", "structpip__plugin__string__arg__t.html", "structpip__plugin__string__arg__t" ],
    [ "plugin_", "structplugin__.html", "structplugin__" ],
    [ "plugin_manager_t", "structplugin__manager__t.html", "structplugin__manager__t" ],
    [ "policy_id_list_", "structpolicy__id__list__.html", "structpolicy__id__list__" ],
    [ "validator_report_t", "structvalidator__report__t.html", "structvalidator__report__t" ]
];